# The blog configuration 

name: ITM 352 BLOG
description: This is where ITM 352 posts their blog stuff
author: Me
permalink: /blog/:title/
timezone: Europe/Berlin

email: me@domain.com
twitter: mytwitteraccount

# This is the default that's used to preview.
# Change this to your website's URL when you publish your site.
url: https://dport96.github.io/ITM352-BLOG
theme: jekyll-theme-modernist
